//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Inspections = new HashSet<Inspection>();
            this.Rents = new HashSet<Rent>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string ChasisNumber { get; set; }
        public string EngineNumber { get; set; }
        public string LicensePlateNumber { get; set; }
        public int CarTypeId { get; set; }
        public int MakeId { get; set; }
        public int ModelId { get; set; }
        public int FuelTypeId { get; set; }
        public int StatusId { get; set; }
        public bool Status { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual CarType CarType { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual Make Make { get; set; }
        public virtual Model Model { get; set; }
        public virtual CarStatu CarStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rents { get; set; }
    }
}
