//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public int CustomerId { get; set; }
        public bool Scratches { get; set; }
        public int FuelQuantityId { get; set; }
        public bool ResponseRubber { get; set; }
        public bool Cat { get; set; }
        public bool GlassBreak { get; set; }
        public int RubberStatus1 { get; set; }
        public int RubberStatus2 { get; set; }
        public int RubberStatus3 { get; set; }
        public int RubberStatus4 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int EmployeeId { get; set; }
        public bool Status { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual FuelQuantity FuelQuantity { get; set; }
        public virtual RubberStatu RubberStatu { get; set; }
        public virtual RubberStatu RubberStatu1 { get; set; }
        public virtual RubberStatu RubberStatu2 { get; set; }
        public virtual RubberStatu RubberStatu3 { get; set; }
    }
}
